AuctionInterface_Sellers/Models/Auction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInterface_Sellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int Id { get; set; }
        public double Amount { get; set; }
        public Metal_Type Metal { get; set; }
        public double StartingPrice { get; set; }
        public double MinimunBidIncrease { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime ClosingTime { get; set; }
        public Auction_State State { get; set; }
        public int OwnerAccountId { get; set; }
        public Nullable<int> WinnerAccountId { get; set; }
    
        public virtual Account OwnerAccount { get; set; }
        public virtual Account WinnerAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}

AuctionInterface_Sellers/Controllers/AuctioneerController.cs
using AuctionInterface_Sellers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows;

namespace AuctionInterface_Sellers.Controllers
{
    public class AuctioneerController : Controller
    {
        private readonly DataSetManager dataSetManager = new DataSetManager(new Auction_DBEntities());

        [HttpPost]
        public ActionResult SellersPage(string email)
        {
            List<Account> accounts = dataSetManager.GetAccounts();
            List<Auction> allAuctions = new List<Auction>();
            List<Bid> allBids = dataSetManager.GetAllBids();

            try
            {
                Account foundAccount = (from account in accounts
                                        where account.Email == email
                                        select account).ToList().ElementAt(0);

                allAuctions = dataSetManager.GetAuctions();

                ViewBag.AllAuctions = allAuctions;
                ViewBag.Account = foundAccount;
                ViewBag.AllBids = allBids;


                return View();
            }
            catch (ArgumentOutOfRangeException)
            {
                MessageBox.Show($"No Account with the Email: {email} ");
                return Redirect("/");
            }

        }


        public ActionResult AuctionForm(int auctioneerId)
        {
            ViewBag.auctioneerId = auctioneerId;

            return View();
        }

        public ActionResult CreateAuction(int auctioneerId,
            Metal_Type metal_Type,
            double amount,
            double startingPrice,
            double minimumBidIncrement,
            DateTime closingTime,
            string endHour,
            string endMinute
            )
        {

            // TODO Error Handeling - Try parse and/or input validation.

            closingTime = closingTime.AddHours(double.Parse(endHour)).AddMinutes(double.Parse(endMinute));

            Auction auction = new Auction();

            auction.OwnerAccountId = auctioneerId;
            auction.Amount = amount;
            auction.Metal = metal_Type;
            auction.StartingPrice = startingPrice;
            auction.MinimunBidIncrease = minimumBidIncrement;
            auction.StartTime = DateTime.Now;
            auction.ClosingTime = closingTime;
            auction.State = Auction_State.Open;

            dataSetManager.DataSets.Auctions.Add(auction);
            dataSetManager.DataSets.SaveChanges();


            return Redirect("/");
        }

       
    }
}

AuctionInterface_Sellers/Views/Auctioneer/AuctionForm.cshtml
@model AuctionInterface_Sellers.Models.Auction
@using AuctionInterface_Sellers.CustomHtmlHelpers;
@using AuctionInterface_Sellers.Models;

@{

    ViewBag.Title = "AuctionForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int auctionerrId = ViewBag.auctioneerId;
}

<h2>Fill your Auction Form</h2>

@using (Html.BeginForm("CreateAuction", "Auctioneer"))
{
    @Html.AntiForgeryToken()

    <h4>Auction stats</h4>

    <div class="form-group">
        @Html.Hidden("auctioneerId", value: auctionerrId)
    </div>


    <div class="form-group">
        @Html.DropDownList("metal_Type",
                EnumHelper.GetSelectList(typeof(Metal_Type)),
                "Select Metal Type",
                new { @class = "form-control" })


    </div>

    <div class="form-group">
        Amount:
        @Html.TextBox("amount")
        @Html.ValidationMessageFor(model => model.Amount, "Must be a number", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        Starting price:
        @Html.TextBox("startingPrice")
        @Html.ValidationMessageFor(model => model.StartingPrice, "Must be a number", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        Minimum bid increment:
        @Html.TextBox("minimumBidIncrement")
        @Html.ValidationMessageFor(model => model.MinimunBidIncrease, "Must be a number", new { @class = "text-danger" })
    </div>

   
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(model => model.ClosingTime, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DatePicker("closingTime")
            @Html.ValidationMessageFor(model => model.ClosingTime, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-10">
           pick closing time:
            Hour: @Html.TextBox("endHour")
            Minute: @Html.TextBox("endMinute")
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Auction" class="btn btn-default" />
            </div>
        </div>
    </div>

}

AuctionInterface_Sellers/Views/Auctioneer/SellersPage.cshtml
@using AuctionInterface_Sellers.Models;
@{
    ViewBag.Title = "SellersPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Account account = ViewBag.Account;
    List<Auction> auctions = ViewBag.AllAuctions;
    List<Bid> bids = ViewBag.AllBids;



}

<h2>@account.Name's Page</h2>


@using (Html.BeginForm("AuctionForm", "Auctioneer"))
{
    <div class="form-group">
        @Html.Hidden("auctioneerId", value: account.Id)
    </div>
    <div class="buttons">
        <div class="form-group">
            <div class="col-md-10">

                <input type="submit" value="Crate an Auction" class="btn btn-secondary" />

                <h2>All Auctions</h2>
            </div>
        </div>
    </div>
}


<table class="table" cellpadding="0" cellspacing="0">

    <tr>
        <th>Amount</th>
        <th>Metal</th>
        <th>Status</th>
        <th>Closing date</th>
        <th>Top bid</th>

    </tr>

    @* TODO: Clean up *@
    @foreach (Auction auction in auctions)
    {
        string topBid;

        List<Bid> currenAuctionsBidsList = new List<Bid>();

        foreach (Bid bid in bids)
        {
            if (bid.AuctionId == auction.Id)
            {
                currenAuctionsBidsList.Add(bid);
            };
        }

        currenAuctionsBidsList.Sort();

        if(currenAuctionsBidsList.Count == 0)
        {
            topBid = "no bids!";
        }
        else
        {
            topBid = currenAuctionsBidsList.First().Amount.ToString();
        }


        string rowStyle;

        if (auction.OwnerAccountId == account.Id)
        {

            rowStyle = "background-color: forestgreen";

        }
        else
        {
            rowStyle = "";
        }

        <tr style="@rowStyle">

            <td>@auction.Amount g</td>
            <td>@auction.Metal.ToString()</td>
            <td>@auction.State</td>
            <td>@auction.ClosingTime.ToString() </td>
            <td>@topBid</td>



        </tr>
    }
</table>